CREATE TABLE qCategory (`id` INTEGER PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL);
INSERT INTO qCategory(name) VALUES ('main');

CREATE TABLE questions (`id` INT(11) PRIMARY KEY AUTO_INCREMENT, `question` VARCHAR(100) NOT NULL, `category` INT(11) NOT NULL, `sort_order` INT(11) NOT NULL, FOREIGN KEY(category) REFERENCES qCategory(id));
INSERT INTO questions (question, category, sort_order) VALUES ('I stand up for what I believe in.', 1, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel in control of my life and future.', 1, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel good about myself.', 1, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I avoid things that are dangerous or unhealthy.', 1, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I enjoy reading or being read to.', 1, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I build friendships with other people.', 1, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I care about school.', 1, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I do my homework.', 1, 8);
INSERT INTO questions (question, category, sort_order) VALUES ('I stay away from tobacco, alcohol, & other drugs.', 1, 9);
INSERT INTO questions (question, category, sort_order) VALUES ('I enjoy learning.', 1, 10);
INSERT INTO questions (question, category, sort_order) VALUES ('I express my feelings in proper ways.', 2, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel good about my future.', 2, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I seek advice from my parents.', 2, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I deal with frustration in positive ways.', 2, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I overcome challenges in positive ways.', 2, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I think it is important to help other people.', 2, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel safe and secure at home.', 2, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I plan ahead and make good choices.', 2, 8);
INSERT INTO questions (question, category, sort_order) VALUES ('I resist bad influences.', 2, 9);
INSERT INTO questions (question, category, sort_order) VALUES ('I resolve conflicts without anyone getting hurt.', 2, 10);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel valued and appreciated by others.', 3, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I take responsibility for what I do.', 3, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I tell the truth even when it is not easy.', 3, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I accept people who are different from me.', 3, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I feel safe at school.', 3, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I am actively engaged in learning new things.', 3, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I am developing a sense of purpose in my life.', 3, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I am encouraged to try things that might be good for me.', 3, 8);
INSERT INTO questions (question, category, sort_order) VALUES ('I am included in family tasks and decisions.', 3, 9);
INSERT INTO questions (question, category, sort_order) VALUES ('I am helping to make my community a better place.', 3, 10);
INSERT INTO questions (question, category, sort_order) VALUES ('I am involved in a religious group or activity.', 4, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I am developing good health habits.', 4, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I am encouraged to help others.', 4, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I am involved in a sport, club, or other group.', 4, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I am trying to help solve social problems.', 4, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I am given useful roles and responsibilities.', 4, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I am developing respect for other people.', 4, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I am eager to do well in school and other activities.', 4, 8);
INSERT INTO questions (question, category, sort_order) VALUES ('I am sensitive to the needs and feelings of others.', 4, 9);
INSERT INTO questions (question, category, sort_order) VALUES ('I am involved in creative things such as music, theater, or art.', 4, 10);
INSERT INTO questions (question, category, sort_order) VALUES ('I am serving others in my community.', 5, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I am spending quality time at home with parent(s).', 5, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I have friends who set good examples for me.', 5, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a school that gives students clear rules.', 5, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I have adults who are good role models for me.', 5, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a safe neighborhood.', 5, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I have parent (s) who try to help me succeed.', 5, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I have good neighbors who care about me.', 5, 8);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a school that cares about kids and encourages them.', 5, 9);
INSERT INTO questions (question, category, sort_order) VALUES ('I have teachers who urge me to develop and achieve.', 5, 10);
INSERT INTO questions (question, category, sort_order) VALUES ('I have support from adults other than my parents.', 6, 1);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a family that provides me with clear rules.', 6, 2);
INSERT INTO questions (question, category, sort_order) VALUES ('I have parent(s) who urge me to do well in school.', 6, 3);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a family that gives me love and support.', 6, 4);
INSERT INTO questions (question, category, sort_order) VALUES ('I have neighbors who help watch out for me.', 6, 5);
INSERT INTO questions (question, category, sort_order) VALUES ('I have parent(s) who are good at talking with me about things.', 6, 6);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a school that enforces rules fairly.', 6, 7);
INSERT INTO questions (question, category, sort_order) VALUES ('I have a family that knows where I am and what I am doing.', 6, 8);